server:
  port: 30001

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.112.49.158:3306/collie?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: phg
    password: phg

  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    #      hbm2ddl.auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 84998757323-j3om0scseph72tgal0lbhjvcb6l0dsnh.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id:
            client-secret:
            redirect-uri: http://localhost:3000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: af340241291df4f8ed0c64fd9c971b33
            redirect-uri: http://localhost:3000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-url: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    rolling-file-name: "C:/prjLog/localLog.%d{yyyy-MM-dd}.%i.log"
  file:
    name: C:/prjLog/localLog.log
    max-history: 30
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG

jwt:
  token:
    tokenKey: aG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QK
    accessTokenExpireTime: 60000
    refreshTokenExpireTime: 3600000