server:
  port: 30001

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.112.49.158:3306/collie?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: phg
    password: phg

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
#      hbm2ddl.auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true

  redis:
    host: localhost
    port: 6379

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    rolling-file-name: "C:/prjLog/localLog.%d{yyyy-MM-dd}.%i.log"
  file:
    name: C:/prjLog/localLog.log
    max-history: 30
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG

jwt:
  token:
    tokenKey: aG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QK
    accessTokenExpireTime: 60000
    refreshTokenExpireTime: 3600000
