server:
  port: 30001
spring:

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.112.49.158:3306/collie?useUnicode=true&characterEncoding=utf-8
    username: phg
    password: phg

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true

  logging:
    level:
      com.tutorial: debug

jwt:
  secret: aG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QKaG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QK
