server:
  port: 30001

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.112.49.158:3306/collie?useUnicode=true&characterEncoding=utf-8
    username: phg
    password: phg

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true

  logging:
    level:
      com.tutorial: debug

  redis:
    host: localhost
    port: 6379

jwt:
  token:
    accessTokenSecretKey: aG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QK
    accessTokenExpireTime: 1800000
    refreshTokenSecretKey: cmVmcmVzaHRva2Vuc2VjcmV0a2V5Cg==
    refreshTokenExpireTime: 3600000
